# Generated by Django 4.1.5 on 2023-01-17 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_movie_product_info_product_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
